Repository edgexfoundry/ci-management, pull requests merged in 2019-10, with the labels that each got.

#498 Fix: #496 Bug where docker-edgex-vault is excluded from edgex-go push
  shell/edgexfoundry-go-docker-push.sh
Labels: bug, fuji

#501 Add JJB template for docker-edgex-consul
  jjb/consul/edgex-consul.yaml
Labels: enhancement, fuji

#507 Update JJB templates for Fuji Release
  jjb/device/device-sdk-c.yaml
  jjb/device/device-sdk-go.yaml
  jjb/device/device-virtual-go.yaml
Labels: fuji

#510 Update JJB for Fuji release of blackbox-tests
  jjb/blackbox-tests/integration-tests.yaml
Labels: fuji

#511 Update JJBs for Fuji release
  jjb/consul/edgex-consul.yaml
  jjb/device/device-snmp-go.yaml
  jjb/ui/edgex-ui-clojure.yaml
  jjb/ui/edgex-ui-go.yaml
  jjb/volume/edgex-volume.yaml
Labels: fuji
