Repository edgexfoundry/ci-management, pull requests merged in 2020-02, with the labels that each got.

#558 Remove docker-edgex-volume JJB
  jjb/volume/edgex-volume.yaml
Labels: geneva

#575 add ARCH check to prevent push from arm64 nodes
  shell/edgex-publish-swagger.sh
Labels: enhancement

#577 remove edgex-go 'master' builds due to new pipeline
  jjb/edgex-go/edgex-go.yaml
Labels: geneva

#578 accommodate the APIKEY being provided as a config file
  shell/edgex-publish-swagger.sh
Labels: bug, geneva

#580 remove edgex-docs master stream due to new pipeline
  jjb/edgex-go/edgex-docs.yaml
Labels: geneva
